# Generated by Django 4.1 on 2023-07-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Workout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part", models.CharField(max_length=20)),
                ("exercises", models.IntegerField()),
                ("duration", models.IntegerField()),
            ],
        ),
    ]
