# Generated by Django 4.1 on 2023-07-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="place",
            field=models.CharField(default="home", max_length=20),
        ),
    ]
