# Generated by Django 4.1 on 2023-07-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0002_workout_place"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pohar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identity", models.IntegerField(default="0")),
                ("location", models.CharField(default="lost", max_length=20)),
                ("name", models.CharField(default="unidentified", max_length=20)),
                ("origin", models.CharField(default="unknown", max_length=64)),
                ("qrcode", models.CharField(max_length=20)),
            ],
        ),
    ]
